#!/bin/sh
set -e

case "$1" in
    remove)
        # leave user projects alone; only note removal
        echo "Amethyst Dev Kit removed. Your .amt files were not touched."
        ;;
    purge)
        ;;
    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
        ;;
esac

exit 0
